export const EcomTableData = [
  {
    id: "1",
    uid: "1",
    product: {
      productName: "Tops and Skirt",
      productDetails: "Skirts are very expensive",
    },
    productImg: "https://mironcoder-hotash.netlify.app/images/product/01.webp",
    category: "Summer Tops and Skirts",
    brand: "Levie's",
    price: {
      originalPrice: "$20.00",
      discountedPrice: "$19.00",
    },
    stock: "30",
    rating: "4.9",
    order: "380",
    sales: "$38k",
  },
  {
    id: "2",
    uid: "2",
    product: {
      productName: "Casual Shirt",
      productDetails: "Breathable cotton shirt",
    },
    productImg: "https://mironcoder-hotash.netlify.app/images/product/02.webp",
    category: "Men's Clothing",
    brand: "Zara",
    price: {
      originalPrice: "$25.00",
      discountedPrice: "$20.00",
    },
    stock: "50",
    rating: "4.6",
    order: "240",
    sales: "$22k",
  },
  {
    id: "3",
    uid: "3",
    product: {
      productName: "Denim Jacket",
      productDetails: "Trendy blue denim jacket",
    },
    productImg: "https://mironcoder-hotash.netlify.app/images/product/03.webp",
    category: "Winter Wear",
    brand: "Levi's",
    price: {
      originalPrice: "$55.00",
      discountedPrice: "$48.00",
    },
    stock: "20",
    rating: "4.8",
    order: "150",
    sales: "$18k",
  },
  {
    id: "4",
    uid: "4",
    product: {
      productName: "Sport Shoes",
      productDetails: "Running shoes with soft sole",
    },
    productImg: "https://mironcoder-hotash.netlify.app/images/product/04.webp",
    category: "Footwear",
    brand: "Nike",
    price: {
      originalPrice: "$60.00",
      discountedPrice: "$54.00",
    },
    stock: "75",
    rating: "4.7",
    order: "410",
    sales: "$49k",
  },
  {
    id: "5",
    uid: "5",
    product: {
      productName: "Women's Handbag",
      productDetails: "Leather medium-sized handbag",
    },
    productImg: "https://mironcoder-hotash.netlify.app/images/product/05.webp",
    category: "Accessories",
    brand: "Coach",
    price: {
      originalPrice: "$90.00",
      discountedPrice: "$85.00",
    },
    stock: "40",
    rating: "4.9",
    order: "390",
    sales: "$52k",
  },
  {
    id: "6",
    uid: "6",
    product: {
      productName: "Formal Trousers",
      productDetails: "Slim-fit black formal pants",
    },
    productImg: "https://picsum.photos/id/1011/400/400",
    category: "Men's Formal",
    brand: "H&M",
    price: {
      originalPrice: "$35.00",
      discountedPrice: "$30.00",
    },
    stock: "60",
    rating: "4.5",
    order: "320",
    sales: "$30k",
  },
  {
    id: "7",
    uid: "7",
    product: {
      productName: "Graphic T-shirt",
      productDetails: "Cool printed cotton tee",
    },
    productImg: "https://picsum.photos/id/1020/400/400",
    category: "T-shirts",
    brand: "Supreme",
    price: {
      originalPrice: "$22.00",
      discountedPrice: "$20.00",
    },
    stock: "100",
    rating: "4.3",
    order: "500",
    sales: "$45k",
  },
  {
    id: "8",
    uid: "8",
    product: {
      productName: "Analog Watch",
      productDetails: "Classic men's leather watch",
    },
    productImg: "https://picsum.photos/id/1005/400/400",
    category: "Watches",
    brand: "Fossil",
    price: {
      originalPrice: "$120.00",
      discountedPrice: "$110.00",
    },
    stock: "30",
    rating: "4.6",
    order: "260",
    sales: "$28k",
  },
  {
    id: "9",
    uid: "9",
    product: {
      productName: "Bluetooth Earbuds",
      productDetails: "Wireless earbuds with noise cancellation",
    },
    productImg: "https://picsum.photos/id/1019/400/400",
    category: "Electronics",
    brand: "Boat",
    price: {
      originalPrice: "$45.00",
      discountedPrice: "$40.00",
    },
    stock: "80",
    rating: "4.4",
    order: "340",
    sales: "$31k",
  },
  {
    id: "10",
    uid: "10",
    product: {
      productName: "Yoga Pants",
      productDetails: "Stretchable workout wear",
    },
    productImg: "https://mironcoder-hotash.netlify.app/images/product/06.webp",
    category: "Activewear",
    brand: "Adidas",
    price: {
      originalPrice: "$30.00",
      discountedPrice: "$27.00",
    },
    stock: "70",
    rating: "4.5",
    order: "390",
    sales: "$33k",
  },
  {
    id: "11",
    uid: "11",
    product: {
      productName: "Kids Toy Car",
      productDetails: "Battery-powered mini vehicle",
    },
    productImg: "https://picsum.photos/id/1010/400/400",
    category: "Kids",
    brand: "HotWheels",
    price: {
      originalPrice: "$80.00",
      discountedPrice: "$75.00",
    },
    stock: "25",
    rating: "4.8",
    order: "210",
    sales: "$22k",
  },
  {
    id: "12",
    uid: "12",
    product: {
      productName: "Office Chair",
      productDetails: "Ergonomic comfort chair",
    },
    productImg: "https://picsum.photos/id/1000/400/400",
    category: "Furniture",
    brand: "GreenSoul",
    price: {
      originalPrice: "$150.00",
      discountedPrice: "$140.00",
    },
    stock: "15",
    rating: "4.6",
    order: "180",
    sales: "$20k",
  },
  {
    id: "13",
    uid: "13",
    product: {
      productName: "Sunglasses",
      productDetails: "UV protection aviator style",
    },
    productImg: "https://picsum.photos/id/1025/400/400",
    category: "Eyewear",
    brand: "RayBan",
    price: {
      originalPrice: "$60.00",
      discountedPrice: "$55.00",
    },
    stock: "35",
    rating: "4.7",
    order: "250",
    sales: "$26k",
  },
  {
    id: "14",
    uid: "14",
    product: {
      productName: "Hair Dryer",
      productDetails: "1200W with cool shot function",
    },
    productImg: "https://picsum.photos/id/1041/400/400",
    category: "Beauty",
    brand: "Philips",
    price: {
      originalPrice: "$35.00",
      discountedPrice: "$32.00",
    },
    stock: "45",
    rating: "4.6",
    order: "230",
    sales: "$21k",
  },
  {
    id: "15",
    uid: "15",
    product: {
      productName: "Backpack",
      productDetails: "Waterproof travel bag",
    },
    productImg: "https://picsum.photos/id/1049/400/400",
    category: "Bags",
    brand: "Wildcraft",
    price: {
      originalPrice: "$40.00",
      discountedPrice: "$35.00",
    },
    stock: "60",
    rating: "4.5",
    order: "310",
    sales: "$29k",
  },
  {
    id: "16",
    uid: "16",
    product: {
      productName: "Laptop Stand",
      productDetails: "Aluminium adjustable stand",
    },
    productImg: "https://picsum.photos/id/1033/400/400",
    category: "Office Accessories",
    brand: "Portronics",
    price: {
      originalPrice: "$25.00",
      discountedPrice: "$22.00",
    },
    stock: "70",
    rating: "4.4",
    order: "290",
    sales: "$24k",
  },
  {
    id: "17",
    uid: "17",
    product: {
      productName: "LED Desk Lamp",
      productDetails: "Rechargeable study lamp",
    },
    productImg: "https://picsum.photos/id/1038/400/400",
    category: "Home Decor",
    brand: "Wipro",
    price: {
      originalPrice: "$30.00",
      discountedPrice: "$28.00",
    },
    stock: "50",
    rating: "4.5",
    order: "270",
    sales: "$23k",
  },
  {
    id: "18",
    uid: "18",
    product: {
      productName: "Smartphone Cover",
      productDetails: "Shockproof and stylish",
    },
    productImg: "https://picsum.photos/id/1050/400/400",
    category: "Mobile Accessories",
    brand: "Spigen",
    price: {
      originalPrice: "$15.00",
      discountedPrice: "$13.00",
    },
    stock: "120",
    rating: "4.2",
    order: "430",
    sales: "$27k",
  },
  {
    id: "19",
    uid: "19",
    product: {
      productName: "Perfume Spray",
      productDetails: "Long-lasting fragrance",
    },
    productImg: "https://picsum.photos/id/1062/400/400",
    category: "Fragrance",
    brand: "Fogg",
    price: {
      originalPrice: "$18.00",
      discountedPrice: "$16.00",
    },
    stock: "80",
    rating: "4.6",
    order: "300",
    sales: "$25k",
  },
  {
    id: "20",
    uid: "20",
    product: {
      productName: "Wireless Mouse",
      productDetails: "Ergonomic USB mouse",
    },
    productImg: "https://picsum.photos/id/1069/400/400",
    category: "Computer Accessories",
    brand: "Logitech",
    price: {
      originalPrice: "$25.00",
      discountedPrice: "$22.00",
    },
    stock: "90",
    rating: "4.7",
    order: "370",
    sales: "$32k",
  },
];
